version: "3.8"
services:
  openai-service:
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: openai
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - openai_part

networks:
  openai_part:
    external: true